// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: lvgl_altimeter_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_MAIN_PAGE
void ui_MAIN_PAGE_screen_init(void);
void ui_event_MAIN_PAGE( lv_event_t * e);
lv_obj_t *ui_MAIN_PAGE;
lv_obj_t *ui_Top_Panel;
lv_obj_t *ui_GPS_Fix;
lv_obj_t *ui_Voltage;
lv_obj_t *ui_Wifi;
lv_obj_t *ui_TempPanel;
lv_obj_t *ui_OAT;
lv_obj_t *ui_Envel_Temp;
lv_obj_t *ui_Vario_Bar;
lv_obj_t *ui_Acceleration_Bar;
lv_obj_t *ui_VAR;
lv_obj_t *ui_Vario_Value;
lv_obj_t *ui_ACC;
lv_obj_t *ui_Alt_Panel1;
lv_obj_t *ui_QNH;
lv_obj_t *ui_QNH_Value;
lv_obj_t *ui_ALT;
lv_obj_t *ui_Alt_Value;
lv_obj_t *ui_Alt_unit;
lv_obj_t *ui_Time;
lv_obj_t *ui_Time1;
lv_obj_t *ui_GPS;
lv_obj_t *ui_TRK_ARC;
lv_obj_t *ui_Track_Value;
lv_obj_t *ui_speed_unit;
lv_obj_t *ui_speed_Value;
lv_obj_t *ui_burnDuration;
lv_obj_t *ui_lastBurn_Cycle;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label10;

// SCREEN: ui_ALT_Plot
void ui_ALT_Plot_screen_init(void);
void ui_event_ALT_Plot( lv_event_t * e);
lv_obj_t *ui_ALT_Plot;
lv_obj_t *ui_Top_Panel1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Altitude_Profile;

// SCREEN: ui_MENU
void ui_MENU_screen_init(void);
void ui_event_MENU( lv_event_t * e);
lv_obj_t *ui_MENU;
lv_obj_t *ui_Top_Panel2;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Parameter_1;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Parameter_2;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Parameter_3;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Parameter_4;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Parameter_5;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Minus_Button;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Plus_Button;
lv_obj_t *ui_Label4;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_MAIN_PAGE( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ALT_Plot, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ALT_Plot_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MENU, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MENU_screen_init);
}
}
void ui_event_ALT_Plot( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MENU, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MENU_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MAIN_PAGE, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MAIN_PAGE_screen_init);
}
}
void ui_event_MENU( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MAIN_PAGE, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MAIN_PAGE_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ALT_Plot, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ALT_Plot_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MAIN_PAGE_screen_init();
ui_ALT_Plot_screen_init();
ui_MENU_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MAIN_PAGE);
}
