// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: lvgl_altimeter_UI

#ifndef _LVGL_ALTIMETER_UI_UI_H
#define _LVGL_ALTIMETER_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MAIN_PAGE
void ui_MAIN_PAGE_screen_init(void);
void ui_event_MAIN_PAGE( lv_event_t * e);
extern lv_obj_t *ui_MAIN_PAGE;
extern lv_obj_t *ui_Top_Panel;
extern lv_obj_t *ui_GPS_Fix;
extern lv_obj_t *ui_Voltage;
extern lv_obj_t *ui_Wifi;
extern lv_obj_t *ui_TempPanel;
extern lv_obj_t *ui_OAT;
extern lv_obj_t *ui_Envel_Temp;
extern lv_obj_t *ui_Vario_Bar;
extern lv_obj_t *ui_Acceleration_Bar;
extern lv_obj_t *ui_VAR;
extern lv_obj_t *ui_Vario_Value;
extern lv_obj_t *ui_ACC;
extern lv_obj_t *ui_Alt_Panel1;
extern lv_obj_t *ui_QNH;
extern lv_obj_t *ui_QNH_Value;
extern lv_obj_t *ui_ALT;
extern lv_obj_t *ui_Alt_Value;
extern lv_obj_t *ui_Alt_unit;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_Time1;
extern lv_obj_t *ui_GPS;
extern lv_obj_t *ui_TRK_ARC;
extern lv_obj_t *ui_Track_Value;
extern lv_obj_t *ui_speed_unit;
extern lv_obj_t *ui_speed_Value;
extern lv_obj_t *ui_burnDuration;
extern lv_obj_t *ui_lastBurn_Cycle;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label10;
// SCREEN: ui_ALT_Plot
void ui_ALT_Plot_screen_init(void);
void ui_event_ALT_Plot( lv_event_t * e);
extern lv_obj_t *ui_ALT_Plot;
extern lv_obj_t *ui_Top_Panel1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Altitude_Profile;
// SCREEN: ui_MENU
void ui_MENU_screen_init(void);
void ui_event_MENU( lv_event_t * e);
extern lv_obj_t *ui_MENU;
extern lv_obj_t *ui_Top_Panel2;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Parameter_1;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Parameter_2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Parameter_3;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Parameter_4;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Parameter_5;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Minus_Button;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Plus_Button;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui____initial_actions0;

LV_FONT_DECLARE( ui_font_Font12);
LV_FONT_DECLARE( ui_font_Font16);
LV_FONT_DECLARE( ui_font_Font20);
LV_FONT_DECLARE( ui_font_Font22);
LV_FONT_DECLARE( ui_font_Font24);
LV_FONT_DECLARE( ui_font_Font26);
LV_FONT_DECLARE( ui_font_Font30);
LV_FONT_DECLARE( ui_font_Font42);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
