// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: imu_baro

#include "../ui/ui.h"
#include "logmacros.hpp"
#include <Fmt.h>

void slider1_change(lv_event_t * e)
{
	LOGI("slider1_change");
}
