// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: lvgl_altimeter_UI

#include "../ui.h"

void ui_ALT_Plot_screen_init(void)
{
ui_ALT_Plot = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ALT_Plot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Top_Panel1 = lv_obj_create(ui_ALT_Plot);
lv_obj_set_width( ui_Top_Panel1, lv_pct(100));
lv_obj_set_height( ui_Top_Panel1, lv_pct(10));
lv_obj_set_align( ui_Top_Panel1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Top_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Top_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Top_Panel1, lv_color_hex(0xB8B8B8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Top_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Top_Panel1);
lv_obj_set_width( ui_Panel1, 100);
lv_obj_set_height( ui_Panel1, 50);
lv_obj_set_x( ui_Panel1, -419 );
lv_obj_set_y( ui_Panel1, 159 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Top_Panel1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Altitude Profile");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Altitude_Profile = lv_chart_create(ui_ALT_Plot);
lv_obj_set_width( ui_Altitude_Profile, 236);
lv_obj_set_height( ui_Altitude_Profile, 163);
lv_obj_set_align( ui_Altitude_Profile, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Altitude_Profile, LV_CHART_TYPE_LINE);
lv_chart_set_axis_tick( ui_Altitude_Profile, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Altitude_Profile, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Altitude_Profile, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
lv_chart_series_t* ui_Altitude_Profile_series_1 = lv_chart_add_series(ui_Altitude_Profile, lv_color_hex(0x00FF21), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Altitude_Profile_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Altitude_Profile, ui_Altitude_Profile_series_1, ui_Altitude_Profile_series_1_array);
lv_chart_series_t* ui_Altitude_Profile_series_2 = lv_chart_add_series(ui_Altitude_Profile, lv_color_hex(0xFA0606), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_Altitude_Profile_series_2_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Altitude_Profile, ui_Altitude_Profile_series_2, ui_Altitude_Profile_series_2_array);

lv_obj_add_event_cb(ui_ALT_Plot, ui_event_ALT_Plot, LV_EVENT_ALL, NULL);

}
