// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: lvgl_altimeter_UI

#include "../ui.h"

void ui_MAIN_PAGE_screen_init(void)
{
ui_MAIN_PAGE = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MAIN_PAGE, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Top_Panel = lv_obj_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_Top_Panel, lv_pct(100));
lv_obj_set_height( ui_Top_Panel, lv_pct(10));
lv_obj_set_align( ui_Top_Panel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Top_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Top_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Top_Panel, lv_color_hex(0xDFC870), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Top_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GPS_Fix = lv_label_create(ui_Top_Panel);
lv_obj_set_width( ui_GPS_Fix, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GPS_Fix, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GPS_Fix, 138 );
lv_obj_set_y( ui_GPS_Fix, lv_pct(-1) );
lv_obj_set_align( ui_GPS_Fix, LV_ALIGN_CENTER );
lv_label_set_text(ui_GPS_Fix,"Sat");
lv_obj_set_style_text_color(ui_GPS_Fix, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GPS_Fix, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_GPS_Fix, &ui_font_Font16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Voltage = lv_label_create(ui_Top_Panel);
lv_obj_set_width( ui_Voltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Voltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Voltage, -120 );
lv_obj_set_y( ui_Voltage, lv_pct(9) );
lv_obj_set_align( ui_Voltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_Voltage,"Voltage");
lv_obj_set_style_text_color(ui_Voltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Voltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Voltage, &ui_font_Font16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Wifi = lv_label_create(ui_Top_Panel);
lv_obj_set_width( ui_Wifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Wifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Wifi, 101 );
lv_obj_set_y( ui_Wifi, lv_pct(2) );
lv_obj_set_align( ui_Wifi, LV_ALIGN_CENTER );
lv_label_set_text(ui_Wifi,"W");
lv_obj_set_style_text_color(ui_Wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Wifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Wifi, &ui_font_Font16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempPanel = lv_obj_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_TempPanel, 88);
lv_obj_set_height( ui_TempPanel, 44);
lv_obj_set_x( ui_TempPanel, lv_pct(35) );
lv_obj_set_y( ui_TempPanel, lv_pct(0) );
lv_obj_clear_flag( ui_TempPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TempPanel, lv_color_hex(0xB8B8B8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OAT = lv_label_create(ui_TempPanel);
lv_obj_set_width( ui_OAT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OAT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OAT, 0 );
lv_obj_set_y( ui_OAT, lv_pct(69) );
lv_obj_set_align( ui_OAT, LV_ALIGN_CENTER );
lv_label_set_text(ui_OAT,"24");
lv_obj_set_style_text_color(ui_OAT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OAT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OAT, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Envel_Temp = lv_label_create(ui_TempPanel);
lv_obj_set_width( ui_Envel_Temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Envel_Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Envel_Temp, 1 );
lv_obj_set_y( ui_Envel_Temp, lv_pct(-58) );
lv_obj_set_align( ui_Envel_Temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_Envel_Temp,"75");
lv_obj_set_style_text_color(ui_Envel_Temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Envel_Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Envel_Temp, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Vario_Bar = lv_bar_create(ui_MAIN_PAGE);
lv_bar_set_range(ui_Vario_Bar, -50,50);
lv_bar_set_value(ui_Vario_Bar,20,LV_ANIM_OFF);
lv_obj_set_width( ui_Vario_Bar, 44);
lv_obj_set_height( ui_Vario_Bar, lv_pct(75));
lv_obj_set_x( ui_Vario_Bar, 137 );
lv_obj_set_y( ui_Vario_Bar, lv_pct(0) );
lv_obj_set_align( ui_Vario_Bar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Vario_Bar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Vario_Bar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Acceleration_Bar = lv_bar_create(ui_MAIN_PAGE);
lv_bar_set_range(ui_Acceleration_Bar, -50,50);
lv_bar_set_value(ui_Acceleration_Bar,-10,LV_ANIM_OFF);
lv_obj_set_width( ui_Acceleration_Bar, 16);
lv_obj_set_height( ui_Acceleration_Bar, lv_pct(75));
lv_obj_set_x( ui_Acceleration_Bar, 103 );
lv_obj_set_y( ui_Acceleration_Bar, lv_pct(0) );
lv_obj_set_align( ui_Acceleration_Bar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Acceleration_Bar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Acceleration_Bar, lv_color_hex(0xA4B0A4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Acceleration_Bar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Acceleration_Bar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Acceleration_Bar, lv_color_hex(0xAA5858), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Acceleration_Bar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_VAR = lv_obj_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_VAR, 46);
lv_obj_set_height( ui_VAR, 28);
lv_obj_set_x( ui_VAR, 137 );
lv_obj_set_y( ui_VAR, 105 );
lv_obj_set_align( ui_VAR, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_VAR, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_VAR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_VAR, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_VAR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_VAR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_VAR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_VAR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Vario_Value = lv_label_create(ui_VAR);
lv_obj_set_width( ui_Vario_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Vario_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Vario_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Vario_Value,"4.5");
lv_obj_set_style_text_color(ui_Vario_Value, lv_color_hex(0xDDE312), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Vario_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Vario_Value, &ui_font_Font24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ACC = lv_obj_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_ACC, 70);
lv_obj_set_height( ui_ACC, 28);
lv_obj_set_x( ui_ACC, 77 );
lv_obj_set_y( ui_ACC, 105 );
lv_obj_set_align( ui_ACC, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ACC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_ACC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ACC, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ACC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ACC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ACC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ACC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ACC, &ui_font_Font16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alt_Panel1 = lv_obj_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_Alt_Panel1, lv_pct(65));
lv_obj_set_height( ui_Alt_Panel1, lv_pct(30));
lv_obj_set_x( ui_Alt_Panel1, lv_pct(0) );
lv_obj_set_y( ui_Alt_Panel1, lv_pct(18) );
lv_obj_clear_flag( ui_Alt_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Alt_Panel1, &ui_font_Font16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_QNH = lv_label_create(ui_Alt_Panel1);
lv_obj_set_width( ui_QNH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_QNH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_QNH, -74 );
lv_obj_set_y( ui_QNH, lv_pct(53) );
lv_obj_set_align( ui_QNH, LV_ALIGN_CENTER );
lv_label_set_text(ui_QNH,"QNH");
lv_obj_set_style_text_color(ui_QNH, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_QNH, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_QNH, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_QNH_Value = lv_label_create(ui_Alt_Panel1);
lv_obj_set_width( ui_QNH_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_QNH_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_QNH_Value, -55 );
lv_obj_set_y( ui_QNH_Value, lv_pct(75) );
lv_obj_set_align( ui_QNH_Value, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_QNH_Value,"1013");
lv_obj_set_style_text_font(ui_QNH_Value, &ui_font_Font20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ALT = lv_label_create(ui_Alt_Panel1);
lv_obj_set_width( ui_ALT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ALT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ALT, -71 );
lv_obj_set_y( ui_ALT, lv_pct(-37) );
lv_obj_set_align( ui_ALT, LV_ALIGN_CENTER );
lv_label_set_text(ui_ALT,"ALT");
lv_obj_set_style_text_color(ui_ALT, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ALT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ALT, &ui_font_Font22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alt_Value = lv_label_create(ui_Alt_Panel1);
lv_obj_set_width( ui_Alt_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Alt_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Alt_Value, -11 );
lv_obj_set_y( ui_Alt_Value, lv_pct(-25) );
lv_obj_set_align( ui_Alt_Value, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_Alt_Value,"12345");
lv_obj_set_style_text_font(ui_Alt_Value, &ui_font_Font42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alt_unit = lv_label_create(ui_Alt_Panel1);
lv_obj_set_width( ui_Alt_unit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Alt_unit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Alt_unit, 89 );
lv_obj_set_y( ui_Alt_unit, lv_pct(-15) );
lv_obj_set_align( ui_Alt_unit, LV_ALIGN_CENTER );
lv_label_set_text(ui_Alt_unit,"ft");
lv_obj_set_style_text_color(ui_Alt_unit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Alt_unit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Alt_unit, &ui_font_Font22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time = lv_obj_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_Time, 95);
lv_obj_set_height( ui_Time, 28);
lv_obj_set_x( ui_Time, -13 );
lv_obj_set_y( ui_Time, 104 );
lv_obj_set_align( ui_Time, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Time, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Time, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time1 = lv_label_create(ui_Time);
lv_obj_set_width( ui_Time1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Time1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Time1,"00:00:00");
lv_obj_set_style_text_font(ui_Time1, &ui_font_Font20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GPS = lv_obj_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_GPS, lv_pct(30));
lv_obj_set_height( ui_GPS, lv_pct(54));
lv_obj_set_x( ui_GPS, lv_pct(-35) );
lv_obj_set_y( ui_GPS, lv_pct(24) );
lv_obj_set_align( ui_GPS, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_GPS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_GPS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GPS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_GPS, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TRK_ARC = lv_spinner_create(ui_GPS,1000,90);
lv_obj_set_width( ui_TRK_ARC, 84);
lv_obj_set_height( ui_TRK_ARC, 92);
lv_obj_set_x( ui_TRK_ARC, 0 );
lv_obj_set_y( ui_TRK_ARC, 16 );
lv_obj_set_align( ui_TRK_ARC, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TRK_ARC,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TRK_ARC, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_TRK_ARC, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_TRK_ARC, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_TRK_ARC, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TRK_ARC, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TRK_ARC, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Track_Value = lv_label_create(ui_GPS);
lv_obj_set_width( ui_Track_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Track_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Track_Value, 0 );
lv_obj_set_y( ui_Track_Value, lv_pct(12) );
lv_obj_set_align( ui_Track_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Track_Value,"090");
lv_obj_set_style_text_font(ui_Track_Value, &ui_font_Font24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speed_unit = lv_label_create(ui_GPS);
lv_obj_set_width( ui_speed_unit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speed_unit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speed_unit, 29 );
lv_obj_set_y( ui_speed_unit, lv_pct(-45) );
lv_obj_set_align( ui_speed_unit, LV_ALIGN_CENTER );
lv_label_set_text(ui_speed_unit,"kt");
lv_obj_set_style_text_color(ui_speed_unit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speed_unit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speed_unit, &ui_font_Font16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speed_Value = lv_label_create(ui_GPS);
lv_obj_set_width( ui_speed_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speed_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speed_Value, 2 );
lv_obj_set_y( ui_speed_Value, lv_pct(-48) );
lv_obj_set_align( ui_speed_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_speed_Value,"25");
lv_obj_set_style_text_font(ui_speed_Value, &ui_font_Font26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_burnDuration = lv_label_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_burnDuration, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_burnDuration, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_burnDuration, lv_pct(22) );
lv_obj_set_y( ui_burnDuration, lv_pct(-35) );
lv_obj_set_align( ui_burnDuration, LV_ALIGN_CENTER );
lv_label_set_text(ui_burnDuration,"0.0s");
lv_obj_set_style_text_font(ui_burnDuration, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lastBurn_Cycle = lv_label_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_lastBurn_Cycle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lastBurn_Cycle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lastBurn_Cycle, lv_pct(22) );
lv_obj_set_y( ui_lastBurn_Cycle, lv_pct(-28) );
lv_obj_set_align( ui_lastBurn_Cycle, LV_ALIGN_CENTER );
lv_label_set_text(ui_lastBurn_Cycle,"0.0s");
lv_obj_set_style_text_font(ui_lastBurn_Cycle, &ui_font_Font12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_Panel2, 59);
lv_obj_set_height( ui_Panel2, 21);
lv_obj_set_x( ui_Panel2, -131 );
lv_obj_set_y( ui_Panel2, -88 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFE1B04), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"MODE");
lv_obj_set_style_text_font(ui_Label1, &ui_font_Font16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_MAIN_PAGE);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_Label10, &ui_font_Font16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_MAIN_PAGE, ui_event_MAIN_PAGE, LV_EVENT_ALL, NULL);

}
