// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: imu_baro

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, lv_pct(100));
lv_obj_set_height( ui_Panel1, lv_pct(100));
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Panel1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"esp32-imu-baro");
lv_obj_set_style_text_font(ui_Label1, &ui_font_headline, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider1 = lv_slider_create(ui_Panel1);
lv_obj_set_width( ui_Slider1, lv_pct(70));
lv_obj_set_height( ui_Slider1, lv_pct(15));
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Slider1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Slider1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Switch1 = lv_switch_create(ui_Panel1);
lv_obj_set_width( ui_Switch1, lv_pct(30));
lv_obj_set_height( ui_Switch1, lv_pct(25));
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Switch1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Switch1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Bar1 = lv_bar_create(ui_Panel1);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, lv_pct(70));
lv_obj_set_height( ui_Bar1, lv_pct(15));
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Bar1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Bar1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);

}
